apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-gke
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: test-gke
      spec:
        containers:
        - name: test-gke
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
          - containerPort: 5000

