name: Test PR Checks with GitHub Actions

on:
  pull_request:
    branches: ['gke', 'master']

jobs:
  pull_request_check:
    name: Pull Request Check
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Setup Python
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test with PyTest
      run: |
        python -m pytest

